### PR TITLE
Fix "this" assignment

### PR DESCRIPTION
**Pull request by ccantill**
Fixes https://github.com/systemjs/builder/issues/655

### CODE REVIEW

**Comment by asapach** [comment]
@frankwallis: please review

**Comment by frankwallis** [comment]
looks good but please can you add this test (into test-build-cache.js):

```
  test('Static build, fetch override with callback', function () {
    var builder = new Builder('test/fixtures/test-tree');
    return builder.buildStatic('cjs.js', {
      fetch: function (load, fetch) {
        return fetch(load);
      }
    });
  });
```

**Comment by guybedford** [comment]
Thanks @frankwallis I've included the test as well for the patch release.

**Comment by frankwallis** [comment]
thanks @ccantill

**Pull request merged**
