### PR TITLE
Option to transpile cjs to es5 with traceur

### PR DESCRIPTION
**Pull request by hmalphettes**
Now that nodejs v4 is out nodejs developers are combining es6 with commonjs modules.
The option `cjs-to-es5` let traceur transpiles that code into es5.

This is useful for:
- minification as uglify-js only supports es5
- supporting other browsers than Chrome.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks for posting. SystemJS will be moving towards https://github.com/systemjs/systemjs/issues/579. 

Unfortunately a patch like this will fail when using transpilers. Also we need to make sure that build features always match SystemJS browser features, so can't create a difference here either.

**Comment by hmalphettes** [comment]
@guybedford thanks for the review.
So what is the best way to proceed until https://github.com/systemjs/systemjs/issues/579 lands?

**Comment by hmalphettes** [comment]
@guybedford "this will fail when using transpilers".
I am not sure I understand that and that is probably good news; maybe I am missing the obvious. When I run `jspm bundle` what should I also do to transpile commonjs-require with es6 into es5 code?

**Comment by guybedford** [comment]
I mean that a lot of users use Babel for compilation instead of Traceur, while this approach only uses Traceur for the transpiling. For now I would suggest running this as a custom precompilation step, perhaps converting `app` to `app-compiled` or something like that.

**Comment by hmalphettes** [comment]
Thanks for your patient explanation.

**Pull request closed without merging**
