### PR TITLE
fixed sourcemaps tests

### PR DESCRIPTION
**Pull request by asapach**
One test is still failing (`'sourceMapContents'`), so it's being skipped.

### CODE REVIEW

**Comment by guybedford** [comment]
Amazing work, thank you! I take it this rules out this `sourcemaps` file for the source maps issues?

**Comment by asapach** [comment]
I'm sorry, could you please rephrase the question?

**Comment by guybedford** [comment]
We're currently investigating a few source maps related issues in https://github.com/systemjs/builder/issues/542 and https://github.com/jspm/jspm-cli/issues/1729. I thought one of those was why you were looking into this!

**Comment by asapach** [comment]
No, I'm still trying to figure out #297, so I'm starting with the tests.
I have indeed noticed some offset issues after traceur compliation, but I'm haven't dug into this.

**Comment by guybedford** [comment]
I managed to fix this by working around Traceur in https://github.com/systemjs/builder/commit/ae5a649083492f50fad550c2f4819cb14874b399. Traceur bug posted in https://github.com/google/traceur-compiler/issues/2109.

**Pull request merged**
