### PR TITLE
upgraded cjs transformer to babel-plugin-transform-cjs-system-wrapper

### PR DESCRIPTION
**Pull request by jrauschenbusch**

### CODE REVIEW

**Comment by guybedford** [comment]
@jrauschenbusch thanks so much for this PR work! It's been amazing to see yourself and @asapach get involved in taking this on, it was really not expected.

@asapach do you have any feedback here at all?

**Comment by asapach** [comment]
LGTM

**Comment by jrauschenbusch** [comment]
@guybedford You are welcome. The opportunity to participate to such an amazing project is thanks enough.

**Comment by guybedford** [comment]
👍

**Comment by guybedford** [comment]
@jrauschenbusch I've invited you to the collaborators team here. Let me know when you've joined and I will give you admin access to transfer the transformer across.

**Comment by jrauschenbusch** [comment]
@guybedford I've joined the collaborators team. :-)

**Comment by guybedford** [comment]
@jrauschenbusch ok you should be able to transfer the repo through now.

**Comment by guybedford** [comment]
@jrauschenbusch this went out in the latest release. I just added a minor modification in https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/commit/6a31c21bcc9b13c15b0f06e7bb9019299533daff.

Could you add me as an npm owner to publish the change? (`npm owner add guybedford babel-plugin-transform-cjs-system-require && npm owner add guybedford babel-plugin-transform-cjs-system-wrapper`).

Thanks!

**Comment by jrauschenbusch** [comment]
@guybedford done!

**Pull request merged**
