### PR TITLE
added test case "can handle multiple transpiled files with same name"

### PR DESCRIPTION
**Pull request by arty-name**
Here is a test case to illustrate an issue I have found: under certain conditions Builder throws an error `Uncaught Error: Mismatched sourcesContent for: amd.js`. 

The background: I have some AMD code which already uses elements of ES6. I try to gradually migrate it to Builder. I use `plugin-babel` do to the transpilation, and I need source maps. However with these requirements two files with identical names cause the Builder to hiccup.

### CODE REVIEW

**Comment by asapach** [comment]
I've stepped through this, and I think the issue is in `plugin-babel` and this PR appears to fix it: systemjs/plugin-babel#71
@guybedford, could you please publish a new release?

**Comment by guybedford** [comment]
@asapach sure I've released plugin-babel 0.0.18. Let me know if that works out ok here.

**Comment by asapach** [comment]
Yup, now tests pass for me. @arty-name try bumping to 0.0.18 to see if it fixes your issue.

**Comment by arty-name** [comment]
Thank you, @guybedford and @asapach, that has resolved the issue. 

Would you like to merge this PR to avoid regressions in the future?

**Comment by guybedford** [comment]
@arty-name sure extra tests can never hurt :) Thanks for your efforts here.

**Comment by arty-name** [comment]
Seems like builds on Node 0.x have failed because of missing module `process`. Does plugin-babel support these versions?

**Comment by guybedford** [comment]
That's just the plugin support yeah. But 0.12 is EOL anyway so it's not a big deal.

**Pull request merged**
