### PR TITLE
Upgrade Traceur to 0.0.84

### LINKED ISSUE #79: Update Traceur
Ideally we can update to 0.0.84 and work out the options to set to get source maps working. If there are issues it would be good to follow them up soon so that Traceur doesn't get held back to 0.0.82 for too long.

### PR DESCRIPTION
**Pull request by crisptrutski**
Closes #79

So the change that's messing us around: https://github.com/google/traceur-compiler/commit/728176734acd0accc99132ed64f6bafa628c243b

Would be nice to make this change more elegantly. Maybe bring in a traceur wrapper namespace, that lets us clean up all the duplication option wrangling too.

### CODE REVIEW

**Comment by guybedford** [comment]
AMAZING. I think I hear Traceur 0.0.85 in the works so would be nice to jump straight to that.

**Comment by crisptrutski** [comment]
OK will update

**Comment by crisptrutski** [comment]
Ah, "in the works". OK will clean this up quickly then park.

**Comment by crisptrutski** [comment]
Less invasive change, with more wiggle-room for future hassles

**Comment by guybedford** [comment]
Nice, we can probably squeeze in even more of the common code into the compile options.

**Comment by crisptrutski** [comment]
@guybedford so 0.0.85 is out, but breaks tests again since 0.0.84. Looking into it, for one thing the number of mapping is huge, they may have broken lowRes option.

**Comment by crisptrutski** [comment]
@guybedford so the changes look benign, correspond to bug fixes.

 Double checked that changes around low res (changed to strict mode) haven't caused issues too.

RE: easing maintenance of file expectations, added check for `UPDATE_EXPECTATIONS` env variable for now.

**Comment by crisptrutski** [comment]
Looks like the `_nodeRequire` fix has lost its mustard too (strange, didn't see the error for a while and now its very common again)

**Comment by guybedford** [comment]
The only thing here that needs to be manually ported still I believe is the expectations resetting.

I really wanted to like the traceur wrapper idea, and even played around with a few variations of compiler utility, but every encapsulation I attempted was either too big or too small. Traceur's compiler API is really best handled directly I think as there are a lot of little things to watch.

**Comment by guybedford** [comment]
Moved the resetting port to being tracked at https://github.com/systemjs/builder/issues/93.

**Pull request closed without merging**
