### PR TITLE
WIP Automated tests

### PR DESCRIPTION
**Pull request by crisptrutski**
(depends on in-memory stuff, will rebase once that's merged)

### CODE REVIEW

**Comment by guybedford** [comment]
Woo!

**Comment by crisptrutski** [comment]
@guybedford 

1. Not sure you'd like tests organized. Went with mocha since that's used in jspm-cli.
    Tests currently run via `mocha test/unit-tests.js` which is a bit clumsy, but otherwise runner will try choke on the other files in `test/`

2. The multiple-files + traceur output is generating some screwy paths. This regression happened during the writing of the tests (took a JSON dump right at the start). Any ideas why spamming `../`?

3. Will add tests exercising the chaining now, just made sense to start with the source files already there

**Comment by crisptrutski** [comment]
Closes #58

**Comment by guybedford** [comment]
Can you add this into the `tests` part of the package.json for an easy run with `npm run test:unit` for example?

**Comment by guybedford** [comment]
Probably advisable to split up the tests into subdirectories now yes.

**Comment by guybedford** [comment]
Are you running Traceur 0.0.82 - I believe there are source maps changes between 0.0.82 and 0.0.84 so we probably need to watch out for that.

**Comment by crisptrutski** [comment]
Yeah I'm using 0.0.82. Do we need to support both or can we bump?

**Comment by guybedford** [comment]
I'm happy to bump up and do a full release through all the projects, just watch the discussions on Traceur as this may change again.

**Pull request closed without merging**
