### PR TITLE
Option forwarding

### PR DESCRIPTION
**Pull request by crisptrutski**
Opts to opt(ion)s, and dust to dust

### CODE REVIEW

**Comment by crisptrutski** [comment]
Nonbreaking, but https://github.com/google/traceur-compiler/pull/1621 may see amendments. We can dangle for a while.

Maybe time to DRY up the opts->options transform.

**Comment by guybedford** [comment]
Nice, happy to merge in the mean time and we can change later.

**Comment by crisptrutski** [comment]
Can I get push here to save admin on my fork? :family:

**Comment by guybedford** [comment]
@crisptrutski sure I've added you.

**Pull request merged**
